In [41]:
# وارد کردن کتابخانه‌ها
import numpy as np
import pandas as pd

# خواندن داده 
df = pd.read_csv("bank-full.csv", sep=";")

# نمایش پنج سطر اول
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [42]:
# نمایش تعداد سطرها و ستون‌ها

print(f"Number os Records: {df.shape[0]:,}")
print(f"Number os Columns: {df.shape[1]:,}")

Number os Records: 45,211
Number os Columns: 17

In [43]:
# نمایش اطلاعات کلی

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  str
 2   marital    45211 non-null  str
 3   education  45211 non-null  str
 4   default    45211 non-null  str
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  str
 7   loan       45211 non-null  str
 8   contact    45211 non-null  str
 9   day        45211 non-null  int64
 10  month      45211 non-null  str
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  str
 16  y          45211 non-null  str
dtypes: int64(7), str(10)
memory usage: 5.9 MB

In [44]:
# نمایش آمار توصیفی تمام ستون‌ها

df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
age,45211.0,NaN,NaN,NaN,40.93621,10.618762,18.0,33.0,39.0,48.0,95.0
job,45211,12,blue-collar,9732,NaN,NaN,NaN,NaN,NaN,NaN,NaN
marital,45211,3,married,27214,NaN,NaN,NaN,NaN,NaN,NaN,NaN
education,45211,4,secondary,23202,NaN,NaN,NaN,NaN,NaN,NaN,NaN
default,45211,2,no,44396,NaN,NaN,NaN,NaN,NaN,NaN,NaN
balance,45211.0,NaN,NaN,NaN,1362.272058,3044.765829,-8019.0,72.0,448.0,1428.0,102127.0
housing,45211,2,yes,25130,NaN,NaN,NaN,NaN,NaN,NaN,NaN
loan,45211,2,no,37967,NaN,NaN,NaN,NaN,NaN,NaN,NaN
contact,45211,3,cellular,29285,NaN,NaN,NaN,NaN,NaN,NaN,NaN
day,45211.0,NaN,NaN,NaN,15.806419,8.322476,1.0,8.0,16.0,21.0,31.0
month,45211,12,may,13766,NaN,NaN,NaN,NaN,NaN,NaN,NaN
duration,45211.0,NaN,NaN,NaN,258.16308,257.527812,0.0,103.0,180.0,319.0,4918.0
campaign,45211.0,NaN,NaN,NaN,2.763841,3.098021,1.0,1.0,2.0,3.0,63.0
pdays,45211.0,NaN,NaN,NaN,40.197828,100.128746,-1.0,-1.0,-1.0,-1.0,871.0
previous,45211.0,NaN,NaN,NaN,0.580323,2.303441,0.0,0.0,0.0,0.0,275.0
poutcome,45211,4,unknown,36959,NaN,NaN,NaN,NaN,NaN,NaN,NaN
y,45211,2,no,39922,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
# مشخص کردن نام ستون هدف
TARGET = "y"

# جدا کردن
X = df.drop(columns=TARGET)

# ذخیره Target در متغیر y
y = df[TARGET]

# نمایش ابعاد
print("Scale of Features:", X.shape)
print("Scale of Target:", y.shape)

# نمایش نام تمام Feature
print("\nList of Features:")
print(X.columns.tolist())

Scale of Features: (45211, 16)
Scale of Target: (45211,)

List of Features:
['age', 'job', 'marital', 'education', 'default', 'balance', 'housing', 'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'poutcome']

In [60]:
# شناسایی Featureهای عددی
numeric_features = X.select_dtypes(include=np.number).columns.tolist()

# شناسایی Featureهای categorical
categorical_features = X.select_dtypes(include="object").columns.tolist()

# نمایش Featureهای عددی
print("Numeric Features:")
print(numeric_features)

# categorical Features
print("\ncategorical Features:")
print(categorical_features)

Numeric Features:
['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous']

categorical Features:
['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome']

C:\Users\hp\AppData\Local\Temp\ipykernel_18344\181299821.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features = X.select_dtypes(include="object").columns.tolist()

In [47]:
# محاسبه تعداد نمونه‌های هر کلاس
target_counts = y.value_counts()

# محاسبه درصد هر کلاس
target_percentages = y.value_counts(normalize=True) * 100

# ساخت یک جدول خلاصه برای بررسی توزیع
target_summary = pd.DataFrame({
    "Count": target_counts,
    "Percent": target_percentages.round(2)
})

# نمایش توزیع 
target_summary

     Count  Percent
y
no   39922     88.3
yes   5289     11.7

In [48]:
# محاسبه تعداد مقادیر خالی
missing_values = df.isnull().sum().sort_values(ascending=False)

# Missing Values
missing_values[missing_values > 0]

Series([], dtype: int64)

In [49]:
# شمارش رکوردهای تکراری
duplicate_count = df.duplicated().sum()

print(f"Duplicates: {duplicate_count:,}")

Duplicates: 0

In [50]:
# ساخت یک جدول برای بررسی نوع داده و تعداد مقادیر یکتا در هر ستون

feature_info = pd.DataFrame({
    "feature": df.columns,
    "dtype": df.dtypes.astype(str),
    "unique_values": df.nunique().values
})

# نمایش جدول اطلاعات Featureها
feature_info

             feature  dtype  unique_values
age              age  int64             77
job              job    str             12
marital      marital    str              3
education  education    str              4
default      default    str              2
balance      balance  int64           7168
housing      housing    str              2
loan            loan    str              2
contact      contact    str              3
day              day  int64             31
month          month    str             12
duration    duration  int64           1573
campaign    campaign  int64             48
pdays          pdays  int64            559
previous    previous  int64             41
poutcome    poutcome    str              4
y                  y    str              2

In [51]:
# categorical Features

for column in categorical_features:

    print(f"\n{'=' * 60}")
    print(f"Column: {column}")

    # نمایش پرتکرارترین مقادیر این ستون
    print(df[column].value_counts(dropna=False).head(15))

============================================================
Column: job
job
blue-collar      9732
management       9458
technician       7597
admin.           5171
services         4154
retired          2264
self-employed    1579
entrepreneur     1487
unemployed       1303
housemaid        1240
student           938
unknown           288
Name: count, dtype: int64

============================================================
Column: marital
marital
married     27214
single      12790
divorced     5207
Name: count, dtype: int64

============================================================
Column: education
education
secondary    23202
tertiary     13301
primary       6851
unknown       1857
Name: count, dtype: int64

============================================================
Column: default
default
no     44396
yes      815
Name: count, dtype: int64

============================================================
Column: housing
housing
yes    25130
no     20081
Name: count, dtype: int64

============================================================
Column: loan
loan
no     37967
yes     7244
Name: count, dtype: int64

============================================================
Column: contact
contact
cellular     29285
unknown      13020
telephone     2906
Name: count, dtype: int64

============================================================
Column: month
month
may    13766
jul     6895
aug     6247
jun     5341
nov     3970
apr     2932
feb     2649
jan     1403
oct      738
sep      579
mar      477
dec      214
Name: count, dtype: int64

============================================================
Column: poutcome
poutcome
unknown    36959
failure     4901
other       1840
success     1511
Name: count, dtype: int64

In [52]:
# نمایش آمار توصیفی Featureهای عددی
# این بخش برای بررسی اولیه دامنه مقادیر و Outlierهای احتمالی مفید است

df[numeric_features].describe().T

,count,mean,std,min,25%,50%,75%,max
age,45211.0,40.936210,10.618762,18.0,33.0,39.0,48.0,95.0
balance,45211.0,1362.272058,3044.765829,-8019.0,72.0,448.0,1428.0,102127.0
day,45211.0,15.806419,8.322476,1.0,8.0,16.0,21.0,31.0
duration,45211.0,258.163080,257.527812,0.0,103.0,180.0,319.0,4918.0
campaign,45211.0,2.763841,3.098021,1.0,1.0,2.0,3.0,63.0
pdays,45211.0,40.197828,100.128746,-1.0,-1.0,-1.0,-1.0,871.0
previous,45211.0,0.580323,2.303441,0.0,0.0,0.0,0.0,275.0

In [53]:
# محاسبه تعداد نمونه‌های هر کلاس
class_counts = y.value_counts()

# محاسبه درصد هر کلاس
class_percentages = y.value_counts(normalize=True) * 100

# ساخت جدول نهایی
class_distribution = pd.DataFrame({
    "Counts": class_counts,
    "Percent": class_percentages.round(2)
})

# نمایش توزیع کلاس‌ها
class_distribution

     Counts  Percent
y
no    39922     88.3
yes    5289     11.7

In [54]:
# بررسی تعداد مقادیر یکتا

cardinality = pd.DataFrame({
    "feature": X.columns,
    "unique_values": X.nunique(),
    "dtype": X.dtypes.astype(str)
})

# مرتب‌سازی بر اساس تعداد مقادیر یکتا
cardinality.sort_values("unique_values", ascending=False)

             feature  unique_values  dtype
balance      balance           7168  int64
duration    duration           1573  int64
pdays          pdays            559  int64
age              age             77  int64
campaign    campaign             48  int64
previous    previous             41  int64
day              day             31  int64
job              job             12    str
month          month             12    str
education  education              4    str
poutcome    poutcome              4    str
marital      marital              3    str
contact      contact              3    str
loan            loan              2    str
default      default              2    str
housing      housing              2    str

In [55]:
# بررسی حداقل، حداکثر، میانگین

numerical_summary = X[numeric_features].describe(
    percentiles=[0.01, 0.25, 0.50, 0.75, 0.99]
).T

numerical_summary

,count,mean,std,min,1%,25%,50%,75%,99%,max
age,45211.0,40.936210,10.618762,18.0,23.0,33.0,39.0,48.0,71.0,95.0
balance,45211.0,1362.272058,3044.765829,-8019.0,-627.0,72.0,448.0,1428.0,13164.9,102127.0
day,45211.0,15.806419,8.322476,1.0,2.0,8.0,16.0,21.0,31.0,31.0
duration,45211.0,258.163080,257.527812,0.0,11.0,103.0,180.0,319.0,1269.0,4918.0
campaign,45211.0,2.763841,3.098021,1.0,1.0,1.0,2.0,3.0,16.0,63.0
pdays,45211.0,40.197828,100.128746,-1.0,-1.0,-1.0,-1.0,-1.0,370.0,871.0
previous,45211.0,0.580323,2.303441,0.0,0.0,0.0,0.0,0.0,8.9,275.0

In [56]:
# نمایش کمترین و بیشترین مقدار

feature_ranges = pd.DataFrame({
    "Min": X[numeric_features].min(),
    "Max": X[numeric_features].max(),
    "Mean": X[numeric_features].mean(),
    "Median": X[numeric_features].median()
})

feature_ranges

           Min     Max         Mean  Median
age         18      95    40.936210    39.0
balance  -8019  102127  1362.272058   448.0
day          1      31    15.806419    16.0
duration     0    4918   258.163080   180.0
campaign     1      63     2.763841     2.0
pdays       -1     871    40.197828    -1.0
previous     0     275     0.580323     0.0

In [57]:
# بررسی نرخ پذیرش سپرده برای هر گروه

categorical_for_eda = [
    "job",
    "marital",
    "education",
    "default",
    "housing",
    "loan",
    "contact",
    "month",
    "poutcome"
]

for column in categorical_for_eda:

    print(f"\n{'=' * 70}")
    print(f"Feature: {column}")

    # محاسبه نرخ yes برای هر دسته
    acceptance_rate = (
        df.groupby(column)["y"]
        .apply(lambda values: (values == "yes").mean() * 100)
        .sort_values(ascending=False)
    )

    print(acceptance_rate.round(2))

======================================================================
Feature: job
job
student          28.68
retired          22.79
unemployed       15.50
management       13.76
admin.           12.20
self-employed    11.84
unknown          11.81
technician       11.06
services          8.88
housemaid         8.79
entrepreneur      8.27
blue-collar       7.27
Name: y, dtype: float64

======================================================================
Feature: marital
marital
single      14.95
divorced    11.95
married     10.12
Name: y, dtype: float64

======================================================================
Feature: education
education
tertiary     15.01
unknown      13.57
secondary    10.56
primary       8.63
Name: y, dtype: float64

======================================================================
Feature: default
default
no     11.80
yes     6.38
Name: y, dtype: float64

======================================================================
Feature: housing
housing
no     16.7
yes     7.7
Name: y, dtype: float64

======================================================================
Feature: loan
loan
no     12.66
yes     6.68
Name: y, dtype: float64

======================================================================
Feature: contact
contact
cellular     14.92
telephone    13.42
unknown       4.07
Name: y, dtype: float64

======================================================================
Feature: month
month
mar    51.99
dec    46.73
sep    46.46
oct    43.77
apr    19.68
feb    16.65
aug    11.01
jun    10.22
nov    10.15
jan    10.12
jul     9.09
may     6.72
Name: y, dtype: float64

======================================================================
Feature: poutcome
poutcome
success    64.73
other      16.68
failure    12.61
unknown     9.16
Name: y, dtype: float64

In [58]:
# Feature مربوط به مدت تماس را از ورودی مدل حذف می‌کنیم
# دلیل: این مقدار بعد از تماس مشخص می‌شود و در سناریوی Prediction
# قبل از تماس در دسترس نیست

LEAKAGE_FEATURES = ["duration"]

# ساخت Featureهای نهایی برای مدل
X_model = X.drop(columns=LEAKAGE_FEATURES)

# Target بدون تغییر باقی می‌ماند
y_model = y.copy()

# نمایش Featureهای نهایی
print("Features used by the model:")
print(X_model.columns.tolist())

print(f"\nFinal Count of Features: {X_model.shape[1]}")

Features used by the model:
['age', 'job', 'marital', 'education', 'default', 'balance', 'housing', 'loan', 'contact', 'day', 'month', 'campaign', 'pdays', 'previous', 'poutcome']

Final Count of Features: 15

In [59]:
# شناسایی Featureهای نهایی
numeric_features_model = (
    X_model
    .select_dtypes(include=np.number)
    .columns
    .tolist()
)

# شناسایی Featureهای categorical نهایی
categorical_features_model = (
    X_model
    .select_dtypes(include="object")
    .columns
    .tolist()
)

print("Numeric Features:")
print(numeric_features_model)

print("\ncategorical Features:")
print(categorical_features_model)

Numeric Features:
['age', 'balance', 'day', 'campaign', 'pdays', 'previous']

categorical Features:
['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome']

C:\Users\hp\AppData\Local\Temp\ipykernel_18344\4116001825.py:12: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  .select_dtypes(include="object")